### ISSUE TITLE
Line UnCentered

### ISSUE THREAD

**Issue by ksdme** [chhabrabhishek/PythonProjects#1]
![imagemagick tmpzgdobj_027](https://cloud.githubusercontent.com/assets/12156014/23590663/305411de-020a-11e7-8fc6-f104e8f7e1a7.png)

The Problem Demanded that the Line Should be Centered.

**Comment by ksdme** [comment]
Please close this issue after you are done.

**Comment by chhabrabhishek** [comment]
Bhai issue resolved , line centered
