### ISSUE TITLE
Some Issue with the Coloring

### ISSUE THREAD

**Issue by ksdme** [chhabrabhishek/PythonProjects#3]
![imagemagick tmpbekzr3_029](https://cloud.githubusercontent.com/assets/12156014/24046259/f05f7c0c-0b47-11e7-9e13-a4a879658c47.png)
First of all **Good Job**, The Replicated Image looks pretty cool!, But On my machine when I executed your script, There were some fine black lines, All over the patterns where color was supposed to change, I hope that it is some calculation mistake. Anyway It would be cool if you rectify it, Anyway this version looks cool enough to be accepted as it is as the solution.

**Comment by chhabrabhishek** [comment]
Thanks man but i checked it and yeah u r right that there r some fine lines but that is not related to logic that might be some calculation mistake so i am up for next challenge plzzz.
